import { constants } from "./index";

const getBoardData = () => {
  return [
    [
      {
        index: 0,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 1,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 2,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 3,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 4,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 5,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 6,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 7,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
    ],
    [
      {
        index: 8,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 9,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 10,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 11,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 12,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 13,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 14,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 15,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
    ],
    [
      {
        index: 16,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 17,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 18,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 19,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 20,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 21,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 22,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 23,
        isKing: false,
        color: constants.MAIN_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
    ],
    [
      {
        index: 24,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 25,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 26,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 27,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 28,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 29,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 30,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 31,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
    ],
    [
      {
        index: 32,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 33,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 34,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 35,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 36,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 37,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 38,
        isKing: false,
        color: "",
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 39,
        isKing: false,
        color: "",
        isLocked: false,
        isAvailable: true,
        showMenu: false,
      },
    ],
    [
      {
        index: 40,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 41,
        isKing: true,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 42,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 43,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 44,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 45,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 46,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 47,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
    ],
    [
      {
        index: 48,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 49,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 50,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 51,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 52,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 53,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 54,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 55,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
    ],
    [
      {
        index: 56,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 57,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 58,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 59,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 60,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 61,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
      {
        index: 62,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: false,
        isAvailable: false,
        showMenu: false,
      },
      {
        index: 63,
        isKing: false,
        color: constants.SECONDARY_PIECE_COLOR,
        isLocked: true,
        isAvailable: true,
        showMenu: false,
      },
    ],
  ];
};

export { getBoardData };
