const MAIN_PIECE_COLOR = "White";
const SECONDARY_PIECE_COLOR = "Red";
const SHOW_POSSIBLE_MOVES = "SHOW_POSSIBLE_MOVES";
const SHOW_POSSIBLE_JUMPS = "SHOW_POSSIBLE_JUMPS";
const SHOW_POSSIBLE_RED_PIECES_MOVES = "SHOW_POSSIBLE_RED_PIECES_MOVES";
const SHOW_POSSIBLE_WHITE_PIECES_MOVES = "SHOW_POSSIBLE_WHITE_PIECES_MOVES";
const LEFT_DIAGONAL_DIRECTION = "LEFT";
const RIGHT_DIAGONAL_DIRECTION = "RIGHT";

// Reducer types
const REFRESH_BOARD = "REFRESH_BOARD";

export {
  MAIN_PIECE_COLOR,
  SECONDARY_PIECE_COLOR,
  SHOW_POSSIBLE_MOVES,
  SHOW_POSSIBLE_JUMPS,
  SHOW_POSSIBLE_WHITE_PIECES_MOVES,
  SHOW_POSSIBLE_RED_PIECES_MOVES,
  RIGHT_DIAGONAL_DIRECTION,
  LEFT_DIAGONAL_DIRECTION,
  REFRESH_BOARD,
};
